site_name: mdatagen
site_description: A Python Library for the Generation of Artificial Missing Data
site_author: ArthurMangussi
repo_name: ArthurMangussi/pymdatagen
repo_url: https://github.com/ArthurMangussi/pymdatagen
edit_uri: ""
use_directory_urls: true
watch:
  - src

nav:
  - Home: index.md  
  - Documentation about Univariate scenario: univariate.md
  - Documentation about Multivariate scenario: multivariate.md
  - MCAR univariate example: mcar_univariate_example.ipynb
  - MNAR univariate example: mnar_univariate_example.ipynb
  - MAR univariate example: mar_univariate_example.ipynb
  - MNAR Multivariate Examples: mnar_multivariate_examples.ipynb
  - Novel MNAR Multivariate mechanism: novel_mnar_multivariate_example.ipynb
  - Evaluation of Imputation Quality: evaluation_imputation_quality.ipynb
  - Visualization Plots: examples_plots.ipynb
  - Complete Pipeline Example: complete_pipeline_example.ipynb
  - API Docs:
      - MAR univariate: api-docs/MAR_univariate.md
      - MCAR univariate: api-docs/MCAR_univariate.md
      - MNAR univariate: api-docs/MNAR_univariate.md
      - MAR multivariate: api-docs/MAR_multivariate.md
      - MCAR multivariate: api-docs/MCAR_multivariate.md
      - MNAR multivariate: api-docs/MNAR_multivariate.md
      - Metrics: api-docs/metrics.md
      - Visualization Plots: api-docs/plots.md
  
  

theme:
  name: material # material, readthedocs, mkdocs
  features:
    - navigation.top
    - navigation.expand
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocs-jupyter:
      execute: False
  - mkdocstrings:
      handlers:
        python:
          # Reference: https://mkdocstrings.github.io/python/usage/
          options:
            # Heading options
            heading_level: 2
            show_root_full_path: False
            show_root_heading: True
            # Member options
            members_order: source # alphabetical, source
            # Docstrings options
            docstring_style: numpy
            docstring_section_style: spacy # table, list, spacy
            line_length: 89
            merge_init_into_class: True
            # Signatures/annotations options
            show_signature_annotations: True
            separate_signature: True
            # Additional options
            show_source: False